# Copyright 2020 Akamai Technologies
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The following env vars are required and should be
# set in Travis:
#
# DOCKER_NAME=akamai/akamai-docker
# DOCKER_USERNAME=xyz
# DOCKER_PASSWORD=xyz
#
# The full list of supported env vars with defaults is here:
# ./scripts/env.sh

# This is optional, specifying for explicitness
os: linux

# We do not need to specify a specific linux distribution.
# Default is xenial at time of writing.
# dist: xenial

# We do not need any specific language runtime,
# minimal provides docker, that is enough
language: minimal

# Enable docker service
services:
  - docker

# We only build master
branches:
  only:
    - master

script:
  - bash ./scripts/docker-login.sh
  - bash ./scripts/docker-build.sh
  - bash ./scripts/docker-push.sh
